//go:build !cli

package main

// Per-app git history. Every app directory becomes a git repo on first
// write; every successful write_file / edit_file MCP call commits the
// change with a meaningful message. This gives agents (and humans)
// honest undo + an audit trail + a future "push to GitHub" lever
// (v2.6.x).
//
// Implementation strategy: shell out to the real `git` binary. The
// alternative (go-git) is heavyweight, lags on edge cases, and
// shell-out matches the user's expectation - `git log` in the app
// directory on the server just works exactly as they'd hope.
//
// What's tracked:
//   - Everything in the app dir EXCEPT data.db / -shm / -wal,
//     .benmore/ backups, uploads/, env.yaml (secrets), and *.log
//   - Initial commit is created from the create_app scaffold
//   - Subsequent commits are one-per-write, message identifies the
//     tool + path: "write_file: flows.yaml", "edit_file: static/app.js (1 replacement)"
//
// What's NOT tracked yet (v2.6.x roadmap):
//   - 30s idle batching of rapid-fire writes into single commits
//   - Auto-restart on revert (currently the caller has to reload)
//   - GitHub remote sync (its own release)

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"
)

// gitMu serializes git operations per app dir. The git index isn't
// safe under concurrent invocations of `git add` / `git commit` (each
// holds a lock on .git/index but exec'ing two side-by-side races).
// A per-dir lock is enough - different apps can commit concurrently.
var (
	gitMuRegistry sync.Map // dir -> *sync.Mutex
)

func gitDirLock(dir string) *sync.Mutex {
	v, _ := gitMuRegistry.LoadOrStore(dir, &sync.Mutex{})
	return v.(*sync.Mutex)
}

// gitAvailable reports whether the `git` binary is present in PATH.
// Cached after first probe so the per-write commit path doesn't pay
// the exec("git --version") cost every time.
var (
	gitProbeOnce      sync.Once
	gitProbeAvailable bool
)

func gitAvailable() bool {
	gitProbeOnce.Do(func() {
		_, err := exec.LookPath("git")
		gitProbeAvailable = err == nil
		if !gitProbeAvailable {
			log.Printf("git: binary not found in PATH - per-app history disabled. Install git on the host to enable.")
		}
	})
	return gitProbeAvailable
}

// gitignoreContents is the .gitignore the framework writes on git
// init. Apps may add their own entries but should not remove these
// without good reason - accidentally committing data.db turns the
// repo into a binary-blob monster on every write.
const gitignoreContents = `# Auto-generated by the framework on git init. Add your own entries
# below, but don't remove these - they protect the repo from runtime
# state that doesn't belong in version control.

# SQLite database + WAL
data.db
data.db-shm
data.db-wal

# Framework backup directory (pre-migrate snapshots)
.benmore/

# Uploaded files
uploads/

# Secrets - never commit
env.yaml

# Logs
*.log

# Developer workspace pre-v2.7.162 binaries seeded into HOME on every
# command - on the fleet HOME is the app dir, so this landed inside the
# app tree (0700, unreadable by the router's git/rsync). Never code.
/Benmore/
`

// gitEnsureRepo initializes the app dir as a git repo if it isn't
// already one, writes .gitignore, and creates the initial commit.
// Idempotent - safe to call on every write.
func gitEnsureRepo(dir, displayName string) error {
	if !gitAvailable() {
		return nil
	}
	gitDir := filepath.Join(dir, ".git")
	if st, err := os.Stat(gitDir); err == nil && st.IsDir() {
		return nil // already initialized
	}
	if _, err := gitRun(dir, "init", "-q", "-b", "main"); err != nil {
		return fmt.Errorf("git init: %w", err)
	}
	// Local repo identity. Avoids "fatal: empty ident name" when the
	// host has no global git config.
	gitRun(dir, "config", "user.email", "benmore@localhost")
	gitRun(dir, "config", "user.name", "Benmore")
	// Quiet commit signing if the host has commit.gpgsign=true globally.
	gitRun(dir, "config", "commit.gpgsign", "false")

	gitignorePath := filepath.Join(dir, ".gitignore")
	if _, err := os.Stat(gitignorePath); err != nil {
		if err := os.WriteFile(gitignorePath, []byte(gitignoreContents), 0644); err != nil {
			return fmt.Errorf("write .gitignore: %w", err)
		}
	}
	if _, err := gitRun(dir, "add", "."); err != nil {
		return fmt.Errorf("git add: %w", err)
	}
	msg := "Initial commit"
	if displayName != "" {
		msg = "Initial commit: " + displayName
	}
	if _, err := gitRun(dir, "commit", "-q", "--allow-empty", "-m", msg); err != nil {
		return fmt.Errorf("git commit (initial): %w", err)
	}
	return nil
}

// gitAutoCommit stages everything in the app dir and creates a commit
// with the provided message. If there are no staged changes (the file
// was identical to the previous version), the commit is skipped
// silently - `git commit` would error with "nothing to commit" but
// that's noise to the agent, not a real failure.
func gitAutoCommit(dir, msg string) {
	if !gitAvailable() || dir == "" {
		return
	}
	mu := gitDirLock(dir)
	mu.Lock()
	defer mu.Unlock()

	// Lazy init - if the app was created before per-app git existed,
	// the first write becomes its initial commit.
	if err := gitEnsureRepo(dir, ""); err != nil {
		log.Printf("git: ensure repo %s: %s", dir, err)
		return
	}

	if _, err := gitRun(dir, "add", "."); err != nil {
		log.Printf("git: add %s: %s", dir, err)
		return
	}
	// Anything to commit?
	out, _ := gitRun(dir, "status", "--porcelain")
	if strings.TrimSpace(out) == "" {
		return
	}
	if _, err := gitRun(dir, "commit", "-q", "-m", msg); err != nil {
		log.Printf("git: commit %s: %s", dir, err)
	}
}

// gitSnapshotHead commits dir's current working tree (lazy-initing the repo and
// committing only if there's something uncommitted) and returns the resulting
// HEAD SHA. It is the pre-image guard before a destructive overwrite (promote,
// refresh-dev, seed-dev): once the prior code is committed, a stomp - wrong
// direction, partial rsync, surprise - is always one `git reset`/`git_revert`
// away. Returns ("", false) when git is unavailable or the dir has no commit yet
// (a fresh/empty destination - nothing to roll back to).
func gitSnapshotHead(dir, msg string) (string, bool) {
	if !gitAvailable() || dir == "" {
		return "", false
	}
	gitAutoCommit(dir, msg) // lazy-init + commit iff dirty; serializes internally
	mu := gitDirLock(dir)
	mu.Lock()
	defer mu.Unlock()
	out, err := gitRun(dir, "rev-parse", "HEAD")
	if err != nil {
		return "", false // no commits yet - nothing to restore to
	}
	return strings.TrimSpace(out), true
}

// gitHardRestore resets dir's TRACKED files back to sha (a value previously
// returned by gitSnapshotHead). Used to roll a destination back after a failed
// or partial overwrite. Gitignored paths (data.db, uploads/, .benmore/) are NOT
// touched - this only undoes code damage, never data. Best-effort.
func gitHardRestore(dir, sha string) error {
	if !gitAvailable() || dir == "" || sha == "" {
		return nil
	}
	mu := gitDirLock(dir)
	mu.Lock()
	defer mu.Unlock()
	_, err := gitRun(dir, "reset", "--hard", sha)
	return err
}

// GitCommit is the read shape returned by gitLog. Mirrors `git log
// --format=%H|%h|%an|%ad|%s` parsed back into a typed record so
// callers don't have to deal with the raw `git` stdout.
type GitCommit struct {
	SHA      string `json:"sha"`
	ShortSHA string `json:"short_sha"`
	Author   string `json:"author"`
	AuthorAt string `json:"author_at"`
	Message  string `json:"message"`
	NumFiles int    `json:"files_changed"`
}

// gitLog returns the last `limit` commits, newest first. limit <= 0
// uses a sane default (50). Empty result for an uninitialized repo -
// not an error, just an honest "no history yet".
func gitLog(dir string, limit int) ([]GitCommit, error) {
	if !gitAvailable() {
		return nil, fmt.Errorf("git: binary not installed on host")
	}
	if _, err := os.Stat(filepath.Join(dir, ".git")); err != nil {
		return nil, nil
	}
	if limit <= 0 {
		limit = 50
	}
	// `%x1f` is ASCII unit separator - safe inside commit messages
	// (commits never contain it; commas/pipes/newlines do).
	const sep = "\x1f"
	out, err := gitRun(dir, "log", "-n", strconv.Itoa(limit),
		"--pretty=format:%H"+sep+"%h"+sep+"%an"+sep+"%ad"+sep+"%s",
		"--date=iso-strict")
	if err != nil {
		return nil, err
	}
	var commits []GitCommit
	for _, line := range strings.Split(strings.TrimSpace(out), "\n") {
		if line == "" {
			continue
		}
		parts := strings.SplitN(line, sep, 5)
		if len(parts) < 5 {
			continue
		}
		commit := GitCommit{
			SHA: parts[0], ShortSHA: parts[1], Author: parts[2],
			AuthorAt: parts[3], Message: parts[4],
		}
		// Fetch the file-change count cheaply via `git show --stat`.
		// Cap at one extra exec per row - for a 50-row log that's
		// ~50ms total, which is fine. Drop in a future pass if it
		// becomes a bottleneck (could parse from --numstat in the
		// main log call).
		if stat, err := gitRun(dir, "show", "--stat", "--format=", parts[0]); err == nil {
			commit.NumFiles = countStatFiles(stat)
		}
		commits = append(commits, commit)
	}
	return commits, nil
}

// gitShow returns the unified diff for a single commit. SHA is
// validated by `git`'s normal resolution - short SHAs, HEAD, and
// HEAD~N all work.
func gitShow(dir, sha string) (string, error) {
	if !gitAvailable() {
		return "", fmt.Errorf("git: binary not installed on host")
	}
	if sha == "" {
		return "", fmt.Errorf("git: sha is required")
	}
	return gitRun(dir, "show", sha)
}

// gitRevert makes the working tree match `sha` exactly and records a
// NEW commit on top of HEAD. This is the safe form of "go back to
// that version" - history is preserved, never rewritten.
//
// Implementation: `git read-tree --reset -u <sha>` resets the index
// AND the working tree to match `sha` (without touching HEAD or the
// reflog). Files added in commits between `sha` and HEAD are deleted
// from the working tree; files deleted in that range are restored;
// files modified are reset to their `sha` content. Then a normal
// commit records the new HEAD pointing at the rolled-back tree.
//
// The naive `git checkout <sha> -- .` we used earlier only restored
// files that existed in <sha> and silently left newer files alone -
// the revert looked correct in `git log` but the working tree still
// had the post-edit files. read-tree --reset is the correct primitive.
func gitRevert(dir, sha string) (GitCommit, error) {
	if !gitAvailable() {
		return GitCommit{}, fmt.Errorf("git: binary not installed on host")
	}
	mu := gitDirLock(dir)
	mu.Lock()
	defer mu.Unlock()

	if _, err := gitRun(dir, "read-tree", "--reset", "-u", sha); err != nil {
		return GitCommit{}, fmt.Errorf("git read-tree: %w", err)
	}
	msg := fmt.Sprintf("revert to %s", sha)
	if _, err := gitRun(dir, "commit", "-q", "--allow-empty", "-m", msg); err != nil {
		return GitCommit{}, fmt.Errorf("git commit (revert): %w", err)
	}
	// Return the freshly-created HEAD as the caller's confirmation.
	commits, err := gitLog(dir, 1)
	if err != nil || len(commits) == 0 {
		return GitCommit{SHA: "HEAD", Message: msg, AuthorAt: time.Now().UTC().Format(time.RFC3339)}, nil
	}
	return commits[0], nil
}

// gitRun is the low-level exec helper. Captures combined stdout/stderr
// (git's user-facing output sometimes goes to stderr) and returns it
// as a string. err is non-nil if git exited non-zero.
//
// `-c safe.directory=<dir>` is prepended on every invocation. The
// production deploy chowns app directories to a per-app DynamicUser
// after the framework writes the initial scaffold, so the router
// process (running as the platform user) and the .git directory
// (owned by the per-app user) belong to different uids. Git's
// 2.35+ "dubious ownership" check would otherwise refuse to operate
// on the repo at all. safe.directory tells git "yes I know, run it
// anyway" for this specific path - narrower than the global `*`
// allowlist, scoped to one operation at a time.
func gitRun(dir string, args ...string) (string, error) {
	full := append([]string{"-c", "safe.directory=" + dir}, args...)
	cmd := exec.Command("git", full...)
	cmd.Dir = dir
	// Strip the inherited HOME / XDG_CONFIG_HOME because:
	//   1. Production runs as the `benmore` user whose home dir
	//      (the service user's ~/.config/git) is locked down - git
	//      otherwise prints "warning: unable to access '.../attributes':
	//      Permission denied" on EVERY invocation, and we capture
	//      stderr into the diff output the dashboard renders.
	//   2. We don't want users' global git config (templates, signing
	//      keys, aliases) leaking into the framework's automated commits.
	// Pointing HOME at /tmp + setting GIT_CONFIG_NOSYSTEM=1 makes git
	// run in a clean, deterministic environment with no warnings.
	env := []string{}
	for _, kv := range os.Environ() {
		// Drop the noisy three; keep PATH so `git` resolves.
		if strings.HasPrefix(kv, "HOME=") ||
			strings.HasPrefix(kv, "XDG_CONFIG_HOME=") ||
			strings.HasPrefix(kv, "GIT_CONFIG_GLOBAL=") {
			continue
		}
		env = append(env, kv)
	}
	cmd.Env = append(env,
		"HOME=/tmp",             // sandboxed home git can always read
		"GIT_CONFIG_NOSYSTEM=1", // skip /etc/gitconfig
		"GIT_TERMINAL_PROMPT=0", // never block on a credentials prompt
		"GIT_OPTIONAL_LOCKS=0",  // skip the gc/maintenance lock dance
	)
	var buf bytes.Buffer
	cmd.Stdout = &buf
	cmd.Stderr = &buf
	if err := cmd.Run(); err != nil {
		return buf.String(), fmt.Errorf("git %s: %w (%s)", strings.Join(args, " "), err, strings.TrimSpace(buf.String()))
	}
	return buf.String(), nil
}

// countStatFiles parses the trailing "N files changed" summary from
// `git show --stat`. Returns 0 when no summary line is present
// (single-file commits omit the count in older git versions).
func countStatFiles(stat string) int {
	for _, line := range strings.Split(stat, "\n") {
		line = strings.TrimSpace(line)
		// Examples:
		//   "1 file changed, 1 insertion(+)"
		//   "5 files changed, 12 insertions(+), 3 deletions(-)"
		if idx := strings.Index(line, " file"); idx > 0 {
			n, err := strconv.Atoi(strings.TrimSpace(line[:idx]))
			if err == nil {
				return n
			}
		}
	}
	// Fallback: count diff stat lines (each starts with a filename).
	n := 0
	for _, line := range strings.Split(stat, "\n") {
		if strings.Contains(line, "|") {
			n++
		}
	}
	return n
}
